spring.application.name=Tikito

# Load local environment variables
spring.config.import=optional:file:./.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true


jwt.secret=${JWT_SECRET}
jwt.expiration=36000000


cloudinary.cloud-name=${Cloud-Name}
cloudinary.api-key=${Cloudinary-Api-Key}
cloudinary.api-secret=${Cloudinary-Api-Secret}


# For Email Service
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# For razorpay
razorpay.key.id=${RAZORPAY_ID}
razorpay.key.secret=${RAZORPAY_SECRET}
